### ISSUE TITLE
[Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.

### ISSUE THREAD

**Issue by sgraber** [nanodlp/ui#1]
Downloaded Win10 zip. Unzipped and ran the webserver.exe from a terminal.  Navigating to 127.0.0.1:8080 results in this response from the page displayed in Chrome:

<pre>[Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
</pre>

And here is the text dumped to the terminal:

2016/03/29 17:41:12.542806 {"Layer":"0","module":"JSON","level":"Warning","msg":"Skipping public/status.json file. GetFileAttributesEx public/status.json: The system cannot find the path specified. "}
2016/03/29 17:41:12.545808 {"Layer":"0","module":"JSON","level":"Error","msg":"Could Not Write to Status JSON File open public/status.json: The system cannot find the path specified. "}
2016/03/29 17:41:12.546809 {"Layer":"0","module":"JSON","level":"Warning","msg":"Skipping db/plates.json file. GetFileAttributesEx db/plates.json: The system cannot find the file specified. "}
2016/03/29 17:41:12.547309 {"Layer":"0","module":"JSON","level":"Warning","msg":"Skipping db/custom-inputs.json file. GetFileAttributesEx db/custom-inputs.json: The system cannot find the file specified. "}
2016/03/29 17:41:12.547309 {"Layer":"0","module":"SLAVE","level":"Error","msg":"Serial port could not be activated The system cannot find the path specified. "}
2016/03/29 17:41:12.547810 {"Layer":"0","module":"Shutter","level":"Error","msg":"Pipe Access Problem open /dev/pigpio: The system cannot find the path specified. "}
2016/03/29 17:41:20.039381 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:20.040881 http: multiple response.WriteHeader calls
2016/03/29 17:41:50.869639 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:50.870638 http: multiple response.WriteHeader calls
2016/03/29 17:41:55.041524 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:55.042486 http: multiple response.WriteHeader calls
2016/03/29 17:41:56.545881 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:56.547386 http: multiple response.WriteHeader calls
2016/03/29 17:41:57.328093 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:57.329594 http: multiple response.WriteHeader calls
2016/03/29 17:41:57.585063 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:57.586050 http: multiple response.WriteHeader calls
2016/03/29 17:41:57.773258 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:57.773758 http: multiple response.WriteHeader calls
2016/03/29 17:41:58.054052 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:58.055043 http: multiple response.WriteHeader calls
2016/03/29 17:41:58.201039 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:55 (0x4177bd)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:41:58.202341 http: multiple response.WriteHeader calls
2016/03/29 17:42:01.298292 PANIC: [Error (where: fromfile) in upnp.xml] open upnp.xml: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:762 (0x41f1f1)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:42:01.298789 http: multiple response.WriteHeader calls
2016/03/29 17:42:55.443847 PANIC: [Error (where: fromfile) in upnp.xml] open upnp.xml: The system cannot find the file specified.
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:273 (0x611e60)
/usr/local/go/src/runtime/asm_386.s:488 (0x47315a)
/usr/local/go/src/runtime/panic.go:426 (0x44e3fd)
/home/shahin/go/src/github.com/plimble/copter/copter.go:61 (0x6e3a33)
/home/shahin/go/src/github.com/plimble/ace-contrib/pongo2/pongo2.go:24 (0x5c8c91)
/home/shahin/go/src/github.com/plimble/ace/context.go:89 (0x48cfb1)
/home/web/printer/app/web.go:762 (0x41f1f1)
/home/shahin/go/src/github.com/plimble/ace/context.go:130 (0x48d3de)
/home/shahin/go/src/github.com/plimble/ace/router.go:132 (0x490ccd)
/home/shahin/go/src/github.com/julienschmidt/httprouter/router.go:299 (0x612088)
/home/shahin/go/src/github.com/plimble/ace/ace.go:89 (0x48c8ac)
/usr/local/go/src/net/http/server.go:2081 (0x593186)
/usr/local/go/src/net/http/server.go:1472 (0x5904c8)
/usr/local/go/src/runtime/asm_386.s:1585 (0x474f51)
2016/03/29 17:42:55.444331 http: multiple response.WriteHeader calls

**Comment by shahinv** [comment]
@sgraber 
The binary file could not find static resources. (html and etc)

Where did you put binary files? 
You should pull/clone the repo first. After that extract binary to the same folder and run the program.

**Comment by sgraber** [comment]
Here is my folder structure:  https://gyazo.com/e4498c944770e3654922cd2dc6d56e8b

**Comment by shahinv** [comment]
@sgraber looks right. 
Please, check if the index.html file is available in templates/ folder.
Also try running executable with admin permission. I have try it on older version of windows.

Also try access following links to see if they works.
http://127.0.0.1:8080/favicon.ico
http://127.0.0.1:8080/status

**Comment by sgraber** [comment]
index.html exists in /templates.

http://127.0.0.1:8080/status yields this response:

{"AutoShutdown":false,"Build":"generic\n","Camera":0,"Covered":false,"CurrentHeight":0,"Disk":"","Halt":false,"IP":"169.254.94.198","LayerID":0,"LayerSinceStart":0,"LayerTime":0,"LayersCount":0,"Mem":"","Path":"","Pause":false,"PlateID":0,"Plates":0,"Printing":false,"Proc":"","ResumeID":0,"Serial":"","Up":"","Version":0}

http://127.0.0.1:8080/favicon.ico yields:

not found

I am running the webserver.exe as Administrator.

**Comment by shahinv** [comment]
@sgraber 
I have tested the program on windows 10. It works fine.

Only important error is this line. 
` 2016/03/29 17:41:57.328093 PANIC: [Error (where: fromfile) in index.html] open index.html: The system cannot find the file specified.`

We have two groups of files. Files inside zip archive and files on the repo.
What is clear from the log is the program could access build file in root folder and other ones which are extracted from zip archive. But it could not access files which sourced from repo even-though they have correct path.

Maybe files cloned from github has different permission. Try each step separately to see if they make any difference.
1. Change files permission specially for templates/ and public/ folders. 
2. If you have any security program disable them to see if they would make any effect. 
3. Also zip whole folder and extract folder somewhere else to see if it makes any effect.

**Comment by adambx** [comment]
fyi, windows 10 x64 here, all working fine
